default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  database: <%= ENV.fetch("DB_NAME", "counters_development") %>
  username: <%= ENV.fetch("DB_USER", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: counters_development

test:
  <<: *default
  database: counters_test

production:
  primary:
    <<: *default
  cache:
    <<: *default
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    migrations_paths: db/cable_migrate
